myfridge/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"


urlpatterns = [
    path("post/create/", views.PostCreateView.as_view(), name="create_post"),
    path("post/update/<int:pk>/", views.PostUpdateView.as_view(), name="update_post"),
    path("post/delete/<int:pk>/", views.PostDeleteView.as_view(), name="delete_post"),
    path("", views.PostListView.as_view(), name="post_list"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path(
        "comment/create/<int:post_id>/",
        views.CommentCreateView.as_view(),
        name="create_comment",
    ),
    path(
        "comment/update/<int:pk>/",
        views.CommentUpdateView.as_view(),
        name="update_comment",
    ),
    path(
        "comment/delete/<int:pk>/",
        views.CommentDeleteView.as_view(),
        name="delete_comment",
    ),
]

myfridge/dishes/urls.py
from django.urls import path
from . import views

app_name = "dishes"


urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("dish/<int:pk>/", views.DishDetailView.as_view(), name="dish-detail"),
    path("dish/random/", views.RandomDishView.as_view(), name="random-dish"),
    path("dish/create/", views.DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/delete", views.DeleteDishView.as_view(), name="dish-delete"),
    path("dish/<int:pk>/update", views.UpdateDishView.as_view(), name="dish-update"),
    path(
        "dish/<int:pk>/send-ingredients",
        views.SendIngredientsView.as_view(),
        name="send-ingredients",
    ),
]

myfridge/fak/urls.py
from django.urls import path
from . import views

app_name = "fak"


urlpatterns = [
    path("", views.FakListView.as_view(), name="fak_home"),
    path("fak/<int:pk>/", views.FakDetailsView.as_view(), name="fak_detail"),
    path("fak/create/", views.FakCreateView.as_view(), name="fak_create"),
    path("fak/update/<int:pk>/", views.FakUpdateView.as_view(), name="fak_update"),
    path("fak/delete/<int:pk>/", views.FakDeleteView.as_view(), name="fak_delete"),
    path("medicine/create", views.MedicineCreateView.as_view(), name="medicine_create"),
    path(
        "medicine/update/<int:pk>/",
        views.MedicineUpdateView.as_view(),
        name="medicine_update",
    ),
    path(
        "medicine/delete/<int:pk>/",
        views.MedicineDeleteView.as_view(),
        name="medicine_delete",
    ),
]

myfridge/myfridge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("", include("dishes.urls")),
    path("social/", include("social.urls")),
    path("contact/", include("contact.urls")),
    path("tools/", include("tools.urls")),
    path("fak/", include("fak.urls")),
    path("blog/", include("blog.urls")),
    path(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myfridge/social/urls.py
from django.urls import path
from . import views

app_name = "social"


urlpatterns = [
    path("dish/<int:pk>/rate-add", views.CreateRateView.as_view(), name="rate-add"),
    path("rate/<int:pk>/update", views.UpdateRateView.as_view(), name="rate-update"),
    path("rate/<int:pk>/delete", views.DeleteRateView.as_view(), name="rate-delete"),
    path("rate/ranking", views.UserRankingView.as_view(), name="user-ranking"),
    path(
        "favourites/add/<int:dish_id>",
        views.AddToFavouritesView.as_view(),
        name="favourite-add",
    ),
    path(
        "favourites/remove/<int:favourite_id>",
        views.DeleteFromFavouriteView.as_view(),
        name="favourite-remove",
    ),
]

myfridge/users/urls.py
from django.urls import path
from . import views

app_name = "users"


urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path(
        "activate/<str:uidb64>/<str:token>/", views.send_activation_url, name="activate"
    ),
    path(
        "register/success", views.SuccessRegisterView.as_view(), name="success_register"
    ),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", views.LogoutUserView.as_view(), name="logout"),
    path("statute/", views.StatuteView.as_view(), name="statute"),
    path(
        "change_password/", views.ChangePasswordView.as_view(), name="change_password"
    ),
    path(
        "change_password_success/",
        views.SuccessPasswordChangeView.as_view(),
        name="success_password_change",
    ),
    path("delete_account/", views.DeleteAccountView.as_view(), name="delete_account"),
    path(
        "delete_account_success/",
        views.SuccessDeleteAccountView.as_view(),
        name="success_delete_account",
    ),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path(
        "profile/update/<int:pk>/",
        views.UpdateProfileView.as_view(),
        name="edit_profile",
    ),
    path(
        "profile/<int:pk>/detail",
        views.ProfileDetailView.as_view(),
        name="profile_detail",
    ),
    path("follow/<int:pk>/", views.FollowUserView.as_view(), name="follow"),
    path("unfollow/<int:pk>/", views.UnfollowUserView.as_view(), name="unfollow"),
    path(
        "profile/<int:user_id>/following",
        views.UserFollowingListView.as_view(),
        name="following",
    ),
    path(
        "profile/<int:user_id>/followers",
        views.UserFollowersListView.as_view(),
        name="followers",
    ),
    path("search/", views.search_users, name="search_users"),
    path("notifications/", views.notifications_list_view, name="notifications"),
    path(
        "notifications/mark_read/",
        views.notifications_mark_as_read,
        name="mark_notification_as_read",
    ),
]

myfridge/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    description = models.CharField(max_length=200, default=None, blank=True, null=True)
    image = models.ImageField(upload_to="images", default=None, blank=True, null=True)
    newsletter = models.BooleanField(default=False)
    points = models.IntegerField(default=0)
    following = models.ManyToManyField(
        "self", through="UserFollowing", related_name="followed_by", symmetrical=False
    )
    dream_weight = models.FloatField(default=0)
    current_weight = models.FloatField(default=0)
    current_height = models.FloatField(default=0)


class UserFollowing(models.Model):
    user_id = models.ForeignKey(
        CustomUser, related_name="follows", on_delete=models.CASCADE
    )
    following_user_id = models.ForeignKey(
        CustomUser, related_name="followed", on_delete=models.CASCADE
    )
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user_id} is following {self.following_user_id}"

myfridge/users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LogoutView
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import (
    CreateView,
    UpdateView,
    TemplateView,
    DetailView,
    ListView,
)
from django.views.generic.edit import FormView
from dotenv import load_dotenv
from .models import CustomUser, UserFollowing
from social.models import Rate
from .forms import (
    CustomUserRegistration,
    CustomUserLogin,
    ChangePasswordForm,
    DeleteAccountForm,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from tools.models import MealDailyPlan
from blog.models import Post, Comment

from .tokens import account_activation_token
from social.models import Feedback
from social.models import FavouriteDish
from blog.models import Post
from dishes.models import Dish

from django.db.models import Q
from notifications.models import Notification
from django.shortcuts import render
from django.contrib import messages

load_dotenv()


class RegisterUserView(FormView):
    form_class = CustomUserRegistration
    template_name = "register.html"
    success_url = reverse_lazy("users:success_register")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.set_password(form.cleaned_data["password"])
        user.save()
        form.send_email(
            message=render_to_string(
                "acc_activate_email.html",
                {
                    "user": user,
                    "domain": get_current_site(self.request).domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": account_activation_token.make_token(user),
                },
            )
        )
        return super().form_valid(form)


def send_activation_url(request: HttpRequest, uidb64: str, token: str) -> HttpResponse:
    """
    The function register_activate() takes in three arguments:
    - request: the request object sent by the user to activate their account
    - idb64: the unique identifier in base64 encoded format
    - token: the token sent in the activation link
    The function attempts to decode the idb64 value and retrieve the corresponding user from the database.
    If the user is found and the token is valid, the user's account is activated, they are logged in,
    and a success message is returned. If the user is not found or the token is invalid, an error message is returned.
    Returns:
        - HttpResponse: A success or error message to be displayed to the user upon attempting to activate their account
    """
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "Your account has been activated!")
        return redirect("dishes:home")
    else:
        messages.error(request, "Invalid activation link")
        return redirect("dishes:home")


class SuccessRegisterView(TemplateView):
    template_name = "success_register.html"


class StatuteView(TemplateView):
    template_name = "statute.html"


class LoginUserView(FormView):
    template_name = "login.html"
    form_class = CustomUserLogin
    success_url = reverse_lazy("dishes:home")

    def form_valid(self, form):
        """
        Overrides the parent class method to log the user in upon successful
        authentication and redirect them to the success URL.
        """
        login(self.request, form.get_user())
        return super().form_valid(form)


class LogoutUserView(LogoutView):
    def get(self, request):
        logout(request)
        return redirect("dishes:home")


class ChangePasswordView(FormView):
    form_class = ChangePasswordForm
    template_name = "change_password.html"
    success_url = reverse_lazy("users:success_password_change")

    def form_valid(self, form):
        try:
            user = CustomUser.objects.get(email=form.cleaned_data["email"])
        except CustomUser.DoesNotExist:
            messages.error(self.request, "User with this email does not exist")
            return super().form_invalid(form)

        if not user.check_password(form.cleaned_data["old_password"]):
            form.add_error("old_password", "Old password is incorrect")
            return super().form_invalid(form)

        user.set_password(form.cleaned_data["new_password"])
        user.is_active = False
        user.save()
        form.send_email(
            message=render_to_string(
                "acc_activate_email.html",
                {
                    "user": user,
                    "domain": get_current_site(self.request).domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": account_activation_token.make_token(user),
                },
            )
        )

        return super().form_valid(form)


class SuccessPasswordChangeView(TemplateView):
    template_name = "password_change_success.html"


class DeleteAccountView(FormView):
    form_class = DeleteAccountForm
    template_name = "delete_account.html"
    success_url = reverse_lazy("users:success_delete_account")

    def form_valid(self, form):  # TODO move this logic to form
        try:
            user = CustomUser.objects.get(email=form.cleaned_data["email"])
        except CustomUser.DoesNotExist:
            messages.error(self.request, "User with this email does not exist")
            return super().form_invalid(form)

        if not user.check_password(form.cleaned_data["password"]):
            messages.error(self.request, "Password is incorrect")
            return super().form_invalid(form)

        user.delete()
        return super().form_valid(form)


class SuccessDeleteAccountView(CreateView):
    template_name = "delete_account_success.html"
    model = Feedback
    fields = ("message",)
    success_url = reverse_lazy("dishes:home")


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        user_dishes = Dish.objects.filter(author=user)
        user_rates = Rate.objects.filter(author=user)
        user_favourite_dish = FavouriteDish.objects.filter(user=user)
        user_blog_post = Post.objects.filter(author=user)
        user_blog_comments = Comment.objects.filter(author=user)

        context = {
            "user": user,
            "user_dishes": user_dishes,
            "user_rates": user_rates,
            "user_favourite_dish": user_favourite_dish,
            "user_blog_post": user_blog_post,
            "user_blog_comments": user_blog_comments,
        }

        return render(request, "profile.html", context)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    fields = (
        "image",
        "description",
        "newsletter",
        "dream_weight",
        "current_weight",
        "current_height",
    )
    template_name = "update_profile.html"
    success_url = reverse_lazy("users:profile")

    def form_valid(self, form):
        messages.success(self.request, "Your profile has been updated!")
        return super().form_valid(form)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.request.user.id)
        return queryset


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = "profile_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_dishes"] = Dish.objects.filter(author=self.object)
        context["user_posts"] = Post.objects.filter(author=self.object)
        context["following_count"] = UserFollowing.objects.filter(
            following_user_id=self.object.id
        ).count()
        context["followers_count"] = UserFollowing.objects.filter(
            user_id=self.object.id
        ).count()
        context["daily_meal_plan"] = MealDailyPlan.objects.filter(is_public=True)
        return context


class FollowUserView(LoginRequiredMixin, View):
    def post(self, request, pk):
        current_user = request.user
        following_user = CustomUser.objects.get(id=pk)
        if current_user == following_user:
            messages.error(request, "You can't follow yourself")
            return redirect("users:profile_detail", pk=following_user.pk)

        UserFollowing.objects.get_or_create(
            user_id=current_user, following_user_id=following_user
        )
        return redirect("users:profile_detail", pk=following_user.pk)


class UnfollowUserView(LoginRequiredMixin, View):
    def post(self, request, pk):
        following_user = CustomUser.objects.get(id=pk)
        UserFollowing.objects.filter(
            user_id=request.user, following_user_id=following_user
        ).delete()
        return redirect("users:profile_detail", pk=following_user.pk)


class UserFollowingListView(LoginRequiredMixin, ListView):
    model = UserFollowing
    template_name = "following_list.html"

    def get_queryset(self):
        user_id = self.kwargs.get("user_id")
        return UserFollowing.objects.filter(user_id=user_id)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

myfridge/users/templates/acc_activate_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration, http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

myfridge/users/templates/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Change password {% endblock %}


{% block content %}


<div class="p-5 mt-5 text-center">
    <h1 class="mb-5">Change password</h1>
</div>


<div class="container mt-5 mb-5">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-success" type="submit">Change password</button>
    </form>
</div>

{% endblock %}

myfridge/users/templates/delete_account.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Delete account {% endblock %}


{% block content %}


<div class="p-5 mt-5 text-center">
    <h1 class="mb-5">Delete Account</h1>
</div>


<div class="container mt-5 mb-5">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-success" type="submit">Delete Account</button>
    </form>
</div>

{% endblock %}

myfridge/users/templates/delete_account_success.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Delete account success {% endblock %}


{% block content %}


<div class="p-5 mt-5 text-center">
    <h1 class="mb-5">Your account has been deleted. Tell us why and what can we do better.</h1>
</div>


<div class="container mt-5 mb-5">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-success" type="submit">Send feedback</button>
    </form>
</div>

{% endblock %}

myfridge/users/templates/followers_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Followers list {% endblock %}

{% block content %}
<div class="container min-vh-100">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center">{{user}}'s Followers</h2>
            <p class="text-center"><a class="btn btn-primary" href="{% url 'users:profile_detail' user.id %}">Back to Profile</a></p>
            {% for user in followed %}
                <div class="col-md-6 offset-md-3">
                    <div class="card mt-3">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'users:profile_detail' user.user_id.id %}">{{user.user_id}}</a></h5>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

myfridge/users/templates/following_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Following list {% endblock %}

{% block content %}
<div class="container min-vh-100">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center">{{user}} is following:</h2>
            <p class="text-center"><a class="btn btn-primary" href="{% url 'users:profile_detail' user.id %}">Back to Profile</a></p>
            {% for user in follows %}
                <div class="col-md-6 offset-md-3">
                    <div class="card mt-3">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'users:profile_detail' user.following_user_id.id %}">{{user.following_user_id}}</a></h5>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

myfridge/users/templates/notifications.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Notifications {% endblock %}

{% block content %}

<div class="container mt-5">
    <ul class="list-group">
        {% for notification in unread_notifications %}
            <li class="list-group-item">
                {{ notification.verb }}
            </li>
        {% empty %}
            <div class="alert alert-info" role="alert">
                <li>No unread notifications.</li>
            </div>
        {% endfor %}
    </ul>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    $.ajax({
        url: '{% url "users:mark_notification_as_read" %}',
        method: 'POST',
        data: {
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
    });
});
</script>

{% endblock %}

myfridge/users/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Profile {% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      {% if user.image %}
      <img class="img-fluid rounded" src="{{user.image.url}}" alt="User Image">
      {% else %}
      <img class="img-fluid rounded" src="https://invisiblechildren.com/wp-content/uploads/2012/07/facebook-profile-picture-no-pic-avatar.jpg" alt="Default User Image">
      {% endif %}
    </div>
    <div class="col-md-6">
      <a class="btn btn-warning" href="{% url 'users:edit_profile' user.id %}">Edit your profile</a>
      <h2>{{user.username}}</h2>
      {% if user.description %}
      <p>{{user.description}}</p>
      {% endif %}
    </div>
  </div>
  {% if user_dishes %}
  <h3>Dishes</h3>

  {% for data in user_dishes %}
  <div class="card mb-3">
    <div class="card-body">
      {{data}}
    </div>
    <div class="card-footer">
      <a class="btn btn-warning" href="{% url 'dishes:dish-update' data.id %}">Update</a>
      <form class="d-inline-block" action="{% url 'dishes:dish-delete' data.id %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Delete</button>
      </form>
    </div>
  </div>
  {% endfor %}
  {% endif %}
  {% if user_rates %}
  <h3>Rates</h3>
  {% for data in user_rates %}
  <div class="card mb-3">
    <div class="card-body">
      {{data}}
    </div>
    <div class="card-footer">
      <a class="btn btn-warning" href="{% url 'social:rate-update' data.id %}">Update</a>
      <form class="d-inline-block" action="{% url 'social:rate-delete' data.id %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Delete</button>
      </form>
    </div>
  </div>
  {% endfor %}
  {% endif %}
  {% if user_favourite_dish %}
  <h3>Favourite Dishes</h3>
  {% for data in user_favourite_dish %}
  <div class="card mb-3">
    <div class="card-body">
      {{data}}
    </div>
    <div class="card-footer">
      <form class="d-inline-block" action="{% url 'social:favourite-remove' data.id %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Delete</button>
      </form>
    </div>
  </div>
  {% endfor %}
  {% endif %}
  {% if user_blog_post %}
  <h3>Posts</h3>
  {% for data in user_blog_post %}
  <div class="card mb-3">
    <div class="card-body">
      {{data}}
    </div>
    <div class="card-footer">
      <a class="btn btn-warning" href="{% url 'blog:update_post' data.id %}">Update</a>
      <form class="d-inline-block" action="{% url 'blog:delete_post' data.id %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Delete</button>
      </form>
    </div>
  </div>
  {% endfor %}
  {% endif %}
  {% if user_blog_comments %}
  <h3>Blog Comments</h3>
  {% for data in user_blog_comments %}
  <div class="card mb-3">
    <div class="card-body">
      {{data}}
    </div>
    <div class="card-footer">
      <a class="btn btn-warning" href="{% url 'blog:update_comment' data.id %}">Update</a>
      <form class="d-inline-block" action="{% url 'blog:delete_comment' data.id %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Delete</button>
      </form>
    </div>
  </div>
  {% endfor %}
  {% endif %}
</div>
{% endblock %}

myfridge/users/templates/profile_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | {{object.username}} {% endblock %}

{% block content %}

<div class="container mt-5">
  <div class="card">
    <div class="card-header bg-primary text-white">
      <h2>{{object.username}}</h2>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">
          {% if object.image %}
          <img class="img-fluid rounded" style="width: 100%;" src="{{object.image.url}}">
          {% else %}
          <img class="img-fluid rounded" style="width: 100%;" src="https://invisiblechildren.com/wp-content/uploads/2012/07/facebook-profile-picture-no-pic-avatar.jpg">
          {% endif %}
        </div>
        <div class="col-md-8">
          <p><strong>Points:</strong> {{object.points}}</p>
          <p><strong>Description:</strong> {{object.description}}</p>
          <p><strong>Following:</strong> <a href="{% url 'users:following' object.id %}">{{ following_count }}</a></p>
          <p><strong>Followers:</strong> <a href="{% url 'users:followers' object.id %}">{{ followers_count }}</a></p>
      {% if request.user in object.followed_by.all %}
        <form method="POST" action="{% url 'users:unfollow' pk=object.id %}">
          {% csrf_token %}
          <input type="submit" class="btn btn-secondary mt-3" value="Unfollow">
        </form>
      {% else %}
          {% if request.user.id is not object.id %}
            <form method="POST" action="{% url 'users:follow' pk=object.id %}">
              {% csrf_token %}
              <input type="submit" class="btn btn-primary mt-3" value="Follow">
            </form>
          {% endif %}
      {% endif %}
        </div>
      </div>
      <h2 style="text-align:center;">New activity</h2>

      {% for dish in user_dishes %}
        <div>
          <h4>{{ dish.name }}</h4>
          {% if dish.image %}
              <img class="card-img-top" style="width: 300px;" src="{{dish.image.url}}" alt="{{ post.name }}">
          {% else %}
              <img class="card-img-top" style="width: 300px;" src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg" alt="No Image">
          {% endif %}
        </div>
      {% endfor %}

      {% for plan in daily_meal_plan %}
        <div>
          <h4>{{plan.date}}</h4>
          {{plan.breakfast}}
          {{plan.second_breakfast}}
          {{plan.lunch}}
          {{plan.tea}}
          {{plan.dinner}}
        </div>
      {% endfor %}

      {% for post in user_posts %}
        <div>
          <h4>{{ post.title }}</h4>
          {% if post.image %}
              <img class="card-img-top" style="width: 300px;" src="{{post.image.url}}" alt="{{ post.name }}">
          {% else %}
              <img class="card-img-top" style="width: 300px;" src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg" alt="No Image">
          {% endif %}
        </div>
      {% endfor %}

    </div>
  </div>
</div>

{% endblock %}

myfridge/users/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Register {% endblock %}


{% block content %}




<div class="container mt-5 mb-5">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <a href="{% url 'users:statute' %}">Statute</a>
        <button class="btn btn-success" type="submit">Register</button>
    </form>
    <a href="{% url 'users:login' %}">If you already have an account, log in here</a>
</div>

{% endblock %}

myfridge/users/templates/search_users_result.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Search {{query}} {% endblock %}

{% block content %}
<div class="container py-5">
    {% if users %}
    <div class="row">
        {% for user in users %}
        <div class="col-md-4 my-2">
            <div class="card">
                <div class="card-body text-center">
                    {% if user.image %}
                    <img class="card-img-top" src="{{user.image.url}}">
                    {% else %}
                    <img class="card-img-top" src="https://invisiblechildren.com/wp-content/uploads/2012/07/facebook-profile-picture-no-pic-avatar.jpg">
                    {% endif %}
                    <h5 class="card-title"><a href="{% url 'users:profile_detail' user.id %}">{{user.username}}</a></h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-danger" role="alert">
        I am sorry there is no any <strong>{{query}}</strong>
    </div>
    {% endif %}
</div>
{% endblock %}

myfridge/users/templates/statute.html
{% extends 'base.html' %}

{% block meta_title%} MyFridge | Statute {% endblock %}


{% block content %}

You agree to...

{% endblock %}

myfridge/users/templates/success_register.html
{% extends 'base.html' %}

{% block meta_title%} MyFridge | Registration success{% endblock %}


{% block content %}



<section style="min-height: 100vh">
    <div style="display: flex; alight-items: center; justify-content: center;">
        <h1>Your account has been created!</h1>
    </div>
    <div style="display: flex; alight-items: center; justify-content: center;">
        <h2>Activate it via the link that has been sent to your email.</h2>
    </div>
</section>

{% endblock %}

myfridge/users/templates/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Update profile {% endblock %}


{% block content %}


<div class="p-5 mt-5 text-center">
    <h1 class="mb-5">Update profile</h1>
</div>


<div class="container">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary" type="submit">Update profile</button>
  <form>
</div>

{% endblock %}