myfridge/dishes/urls.py
from django.urls import path
from . import views

app_name = "dishes"


urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("dish/<int:pk>/", views.DishDetailView.as_view(), name="dish-detail"),
    path("dish/random/", views.RandomDishView.as_view(), name="random-dish"),
    path("dish/create/", views.DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/delete", views.DeleteDishView.as_view(), name="dish-delete"),
    path("dish/<int:pk>/update", views.UpdateDishView.as_view(), name="dish-update"),
    path(
        "dish/<int:pk>/send-ingredients",
        views.SendIngredientsView.as_view(),
        name="send-ingredients",
    ),
]

myfridge/fak/urls.py
from django.urls import path
from . import views

app_name = "fak"


urlpatterns = [
    path("", views.FakListView.as_view(), name="fak_home"),
    path("fak/<int:pk>/", views.FakDetailsView.as_view(), name="fak_detail"),
    path("fak/create/", views.FakCreateView.as_view(), name="fak_create"),
    path("fak/update/<int:pk>/", views.FakUpdateView.as_view(), name="fak_update"),
    path("fak/delete/<int:pk>/", views.FakDeleteView.as_view(), name="fak_delete"),
    path("medicine/create", views.MedicineCreateView.as_view(), name="medicine_create"),
    path(
        "medicine/update/<int:pk>/",
        views.MedicineUpdateView.as_view(),
        name="medicine_update",
    ),
    path(
        "medicine/delete/<int:pk>/",
        views.MedicineDeleteView.as_view(),
        name="medicine_delete",
    ),
]

myfridge/myfridge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("", include("dishes.urls")),
    path("social/", include("social.urls")),
    path("contact/", include("contact.urls")),
    path("tools/", include("tools.urls")),
    path("fak/", include("fak.urls")),
    path("blog/", include("blog.urls")),
    path(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myfridge/social/urls.py
from django.urls import path
from . import views

app_name = "social"


urlpatterns = [
    path("dish/<int:pk>/rate-add", views.CreateRateView.as_view(), name="rate-add"),
    path("rate/<int:pk>/update", views.UpdateRateView.as_view(), name="rate-update"),
    path("rate/<int:pk>/delete", views.DeleteRateView.as_view(), name="rate-delete"),
    path("rate/ranking", views.UserRankingView.as_view(), name="user-ranking"),
    path(
        "favourites/add/<int:dish_id>",
        views.AddToFavouritesView.as_view(),
        name="favourite-add",
    ),
    path(
        "favourites/remove/<int:favourite_id>",
        views.DeleteFromFavouriteView.as_view(),
        name="favourite-remove",
    ),
]

myfridge/users/urls.py
from django.urls import path
from . import views

app_name = "users"


urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path(
        "activate/<str:uidb64>/<str:token>/", views.send_activation_url, name="activate"
    ),
    path(
        "register/success", views.SuccessRegisterView.as_view(), name="success_register"
    ),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", views.LogoutUserView.as_view(), name="logout"),
    path("statute/", views.StatuteView.as_view(), name="statute"),
    path(
        "change_password/", views.ChangePasswordView.as_view(), name="change_password"
    ),
    path(
        "change_password_success/",
        views.SuccessPasswordChangeView.as_view(),
        name="success_password_change",
    ),
    path("delete_account/", views.DeleteAccountView.as_view(), name="delete_account"),
    path(
        "delete_account_success/",
        views.SuccessDeleteAccountView.as_view(),
        name="success_delete_account",
    ),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path(
        "profile/update/<int:pk>/",
        views.UpdateProfileView.as_view(),
        name="edit_profile",
    ),
    path(
        "profile/<int:pk>/detail",
        views.ProfileDetailView.as_view(),
        name="profile_detail",
    ),
    path("follow/<int:pk>/", views.FollowUserView.as_view(), name="follow"),
    path("unfollow/<int:pk>/", views.UnfollowUserView.as_view(), name="unfollow"),
    path(
        "profile/<int:user_id>/following",
        views.UserFollowingListView.as_view(),
        name="following",
    ),
    path(
        "profile/<int:user_id>/followers",
        views.UserFollowersListView.as_view(),
        name="followers",
    ),
    path("search/", views.search_users, name="search_users"),
    path("notifications/", views.notifications_list_view, name="notifications"),
    path(
        "notifications/mark_read/",
        views.notifications_mark_as_read,
        name="mark_notification_as_read",
    ),
]

myfridge/dishes/forms.py
from django import forms
from .models import (
    Country,
    DifficultyLevel,
    DishCategory,
)
from django.urls import reverse
from users.task import send_email_task


class DateSortingForm(forms.Form):
    CHOICES = (("1", "Newest"), ("2", "Oldest"))

    order_by = forms.ChoiceField(
        choices=CHOICES,
        required=False,
    )


class CaloriesSortingForm(forms.Form):
    CHOICES = (("1", "Highest"), ("2", "Lowest"))

    order_by = forms.ChoiceField(
        choices=CHOICES,
        required=False,
    )


class SearchForm(forms.Form):
    search_query = forms.CharField(
        label="Search",
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "Search for dishes"}),
    )


class TimeToMake(forms.Form):
    CHOICES = (("1", "Shortest"), ("2", "Longest"))

    order_by = forms.ChoiceField(
        choices=CHOICES,
        required=False,
    )


class GlutenFilterForm(forms.Form):
    gluten = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["gluten"].label = "Has gluten"


class LactoseFilterForm(forms.Form):
    lactose = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["lactose"].label = "Has lactose"


class MeatFilterForm(forms.Form):
    meat = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["meat"].label = "Has meat"


class VeganFilterForm(forms.Form):
    vegan = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["vegan"].label = "Is vegan"


class VegetarianFilterForm(forms.Form):
    vegetarian = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["vegetarian"].label = "Is vegetarian"


class CountryFilterForm(forms.Form):
    country = forms.ModelChoiceField(queryset=Country.objects.all(), required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["country"].label = "Country"


class DifficultyLevelFilterForm(forms.Form):
    level = forms.ModelChoiceField(
        queryset=DifficultyLevel.objects.all(), required=False
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["level"].label = "Difficulty Level"


class CategoryFilterForm(forms.Form):
    category = forms.ModelChoiceField(
        queryset=DishCategory.objects.all(), required=False
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["category"].label = "Category"


class SendIngredientForm(forms.Form):
    email = forms.EmailField(label="Your email address")
    accept_statute = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields[
            "accept_statute"
        ].help_text = (
            f'<a href="{reverse("contact:contact-statute")}">Read the statute</a>'
        )

    def send_email(self, message):
        send_email_task.delay(
            self.cleaned_data.get("email"),
            subject="List of ingredients",
            message=message,
        )

myfridge/dishes/views.py
from typing import Any, Dict

from django.db.models import Q

from .models import Dish
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    FormView,
)
from social.models import Rate
from .forms import (
    DateSortingForm,
    GlutenFilterForm,
    LactoseFilterForm,
    MeatFilterForm,
    VeganFilterForm,
    VegetarianFilterForm,
    CountryFilterForm,
    DifficultyLevelFilterForm,
    CategoryFilterForm,
    CaloriesSortingForm,
    SearchForm,
    SendIngredientForm,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.contrib import messages


class HomeView(ListView):
    model = Dish
    template_name = "home.html"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()

        search_query = self.request.GET.get("search_query")
        if search_query:
            ingredients = [ingredient.strip() for ingredient in search_query.split(",")]
            conditions = [
                Q(main_ingredient__name__icontains=ingredient)
                for ingredient in ingredients
            ]
            combined_conditions = conditions[0]
            for condition in conditions[1:]:
                combined_conditions |= condition
            queryset = queryset.filter(combined_conditions).distinct()

        order_by = self.request.GET.get("order_by")
        if order_by:
            if order_by == "1":
                queryset = queryset.order_by("date_created")
            if order_by == "2":
                queryset = queryset.order_by("-date_created")

        calories = self.request.GET.get("calories")
        if calories:
            if calories == "1":
                queryset = queryset.order_by("calories")
            if calories == "2":
                queryset = queryset.order_by("-calories")

        time_to_make = self.request.GET.get("time_to_make")
        if time_to_make:
            if time_to_make == "1":
                queryset = queryset.order_by("time_to_make")
            if time_to_make == "2":
                queryset = queryset.order_by("-time_to_make")

        gluten = self.request.GET.get("gluten")
        if gluten:
            queryset = queryset.filter(gluten=True)

        lactose = self.request.GET.get("lactose")
        if lactose:
            queryset = queryset.filter(lactose=True)

        meat = self.request.GET.get("meat")
        if meat:
            queryset = queryset.filter(meat=True)

        vegan = self.request.GET.get("vegan")
        if vegan:
            queryset = queryset.filter(vegan=True)

        vegetarian = self.request.GET.get("vegetarian")
        if vegetarian:
            queryset = queryset.filter(vegetarian=True)

        country = self.request.GET.get("country")
        if country:
            queryset = queryset.filter(country=country)

        level = self.request.GET.get("level")
        if level:
            queryset = queryset.filter(level=level)

        category = self.request.GET.get("category")
        if category:
            queryset = queryset.filter(category=category)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["date_sorting_form"] = DateSortingForm(self.request.GET)
        context["gluten_form"] = GlutenFilterForm(self.request.GET)
        context["lactose_form"] = LactoseFilterForm(self.request.GET)
        context["meat_form"] = MeatFilterForm(self.request.GET)
        context["vegan_form"] = VeganFilterForm(self.request.GET)
        context["vegetarian_form"] = VegetarianFilterForm(self.request.GET)
        context["country_form"] = CountryFilterForm(self.request.GET)
        context["difficulty_level_form"] = DifficultyLevelFilterForm(self.request.GET)
        context["category_form"] = CategoryFilterForm(self.request.GET)
        context["calories_sorting_form"] = CaloriesSortingForm(self.request.GET)
        context["search_form"] = SearchForm(self.request.GET)
        search_query = self.request.GET.get("search_query")
        context["search_query"] = search_query if search_query else None
        return context


class DishDetailView(DetailView):
    model = Dish
    template_name = "dish_details.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["rates"] = Rate.objects.filter(dish=self.object)
        return context


class RandomDishView(DetailView):
    model = Dish
    template_name = "dish_details.html"

    def get_object(self, queryset=None):
        return Dish.objects.order_by("?").first()

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["rates"] = Rate.objects.filter(dish=self.object)
        return context


class SendIngredientsView(FormView):
    template_name = "send_ingredients.html"
    form_class = SendIngredientForm
    success_url = reverse_lazy("dishes:home")

    def form_valid(self, form):
        dish = Dish.objects.get(pk=self.kwargs["pk"])
        main_ingredients = dish.main_ingredient.all()
        other_ingredients = dish.other_ingredients.all()
        main_ingredients_names = ", ".join(
            [str(ingredients) for ingredients in main_ingredients]
        )
        other_ingredients_names = ", ".join(
            [str(ingredients) for ingredients in other_ingredients]
        )

        form.send_email(
            f"{main_ingredients_names} and {other_ingredients_names} are the ingredients of {dish.name}."
        )
        messages.success(self.request, "Message was sent!")
        return redirect(self.get_success_url())


class DishCreateView(LoginRequiredMixin, CreateView):
    model = Dish
    template_name = "dish_create.html"
    fields = (
        "name",
        "time_to_make",
        "description",
        "image",
        "kcal",
        "gluten",
        "lactose",
        "meat",
        "vegetarian",
        "vegan",
        "country",
        "level",
        "main_ingredient",
        "other_ingredients",
        "category",
    )

    def get_success_url(self):
        return reverse_lazy("dishes:dish-detail", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user

        user = self.request.user
        user.points += 10
        user.save()
        messages.success(self.request, "Dish was created! You got 10 points!")
        return super().form_valid(form)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)

        return context


class UpdateDishView(LoginRequiredMixin, UpdateView):
    model = Dish
    template_name = "dish_update.html"
    fields = (
        "name",
        "time_to_make",
        "description",
        "image",
        "kcal",
        "gluten",
        "lactose",
        "meat",
        "vegetarian",
        "vegan",
        "country",
        "level",
        "main_ingredient",
        "other_ingredients",
        "category",
    )

    def get_success_url(self):
        return reverse_lazy("dishes:dish-detail", kwargs={"pk": self.object.pk})

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        if not queryset.exists():
            messages.error(self.request, "You are not authorized to edit this Dish.")
        messages.success(self.request, "Dish was updated!")
        return queryset

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return context


class DeleteDishView(LoginRequiredMixin, DeleteView):
    model = Dish
    success_url = reverse_lazy("dishes:home")

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        if not queryset.exists():
            messages.error(self.request, "You are not authorized to edit this Dish.")
        messages.success(self.request, "Dish was deleted!")
        return queryset

myfridge/dishes/templates/dish_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title %} MyFridge | Dish create {% endblock %}

{% block content %}

<div class="container my-5">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <button class="btn btn-primary" type="submit">Create new dish</button>
    </form>
</div>

{% endblock %}

myfridge/dishes/templates/dish_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Dish {{object.name}} {% endblock %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card my-4">
                <div class="card-body">
                    <h2 class="card-title">{{object.name}} {% if object.get_newest_label %} <strong>Newest</strong> {% endif %}</strong></h2>
                        {% if object.author == user %}
                        <a href="{% url 'dishes:dish-update' object.id %}" class="btn btn-warning">Edit</a>
                        <form action="{% url 'dishes:dish-delete' object.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger mt-2">Delete</button>
                        </form>
                        {% endif %}
                    <p class="card-text"><a href="{% url 'users:profile_detail' object.author.id %}">{{object.author}}</a> | {{object.date_created}}</p>
                    {% if object.image %}
                    <img class="card-img-top img-fluid mx-auto d-block" src="{{object.image.url}}">
                    {% else %}
                    <img class="card-img-top img-fluid mx-auto d-block" src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg">
                    {% endif %}

                    <h3>Main Ingredients:</h3>
                    <a href="{% url 'dishes:send-ingredients' object.id %}" class="btn btn-success">Send Ingredients</a>
                      <ul>
                        {% for ingredient in object.main_ingredient.all %}
                        <li>{{ ingredient }}</li>
                        {% endfor %}
                      </ul>

                      <h3>Other Ingredients:</h3>
                      <ul>
                        {% for ingredient in object.other_ingredients.all %}
                        <li>{{ ingredient }}</li>
                        {% endfor %}
                      </ul>

                      <h3>Can have:</h3>
                      <ul>
                        {% if object.gluten %}
                        <li>Gluten</li>
                        {% endif %}
                        {% if object.lactose %}
                        <li>Lactose</li>
                        {% endif %}
                        {% if object.meat %}
                        <li>Meat</li>
                        {% endif %}
                        {% if object.vegetarian %}
                        <li>Vegetarian</li>
                        {% endif %}
                        {% if object.vegan %}
                        <li>Vegan</li>
                        {% endif %}
                      </ul>

                    <p class="card-text mt-3">{{object.description|safe}}</p>
                </div>
            </div>

            <a href="{% url 'social:rate-add' object.id %}" class="btn btn-success">Add rate</a>
            <div class="mt-4">
            {% if rates %}
            {% for rate in rates %}
                <div class="card my-2">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'users:profile_detail' rate.author.id %}">{{rate.author}}</a> {{rate.choose_rate}} {% if rate.get_newest_label %} <strong>Newest</strong> {% endif %}</h5>
                        <p class="card-text">{{rate.comment}}</p>
                        {% if rate.author == user %}
                          <form method="POST" action="{% url 'social:rate-delete' object.id %}" class="d-inline">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-danger">Delete</button>
                          </form>
                         <a href="{% url 'social:rate-update' object.id %}" class="btn btn-warning">Edit</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            {% else %}
            <p class="my-4">There are no rate yet</p>
            {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

myfridge/dishes/templates/dish_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Dish update {% endblock %}


{% block content %}


<div class="container my-5">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <button class="btn btn-warning" type="submit">Update</button>
    </form>
</div>
{% endblock %}

myfridge/dishes/templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="sidebar">
                <a href="{% url 'dishes:dish-create' %}">Add dish</a>
                <a href="{% url 'dishes:random-dish' %}">Random dish</a>
                <form method="GET" action="">
                    {% csrf_token %}
                    <div>{{ search_form|crispy }}</div>
                    <div>{{ gluten_form|crispy }}</div>
                    <div>{{ lactose_form|crispy }}</div>
                    <div>{{ meat_form|crispy }}</div>
                    <div>{{ vegan_form|crispy }}</div>
                    <div>{{ vegetarian_form|crispy }}</div>
                    <div>{{ date_sorting_form|crispy }}</div>
                    <div>{{ calories_sorting_form|crispy }}</div>
                    <div>{{ country_form|crispy }}</div>
                    <div>{{ difficulty_level_form|crispy }}</div>
                    <div>{{ category_form|crispy }}</div>
                    <button type="submit" class="btn btn-success mt-3">Filter</button>
                </form>
            </div>
        </div>
        <div class="col-md-9">
            {% if object_list %}
            {% for data in object_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <a style="text-decoration: none; color: black;" href="{% url 'dishes:dish-detail' data.id %}" class="h4">{{ data.name }} {% if data.get_newest_label %} <strong>Newest</strong> {% endif %}</a>
                            {% if data.image %}
                                <img class="card-img-top" src="{{data.image.url}}" alt="{{ data.name }}">
                            {% else %}
                                <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg" alt="No Image">
                            {% endif %}
                        </div>
                        <div class="col-md-8">
                            <p><strong>Level:</strong> {{data.level}}</p>
                            <p><strong>Kcal:</strong> {{data.kcal}}</p>
                            <p><strong>Category:</strong> {{data.category}}</p>
                            <p><strong>Time to make:</strong> {{ data.time_to_make }}</p>
                            {% for ingredient in data.main_ingredient.all %}
                                <span style="font-weight: bold; background-color: #cfcfcf; border-radius:25px; padding: 0 15px;" class="
                                    {% if ingredient.name in search_query  %}
                                        text-success
                                    {% else %}
                                        text-black
                                    {% endif %}
                                ">{{ ingredient }}</span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <form action="{% url 'social:favourite-add' data.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">Add to favourite</button>
                    </form>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h5> There is no dishes </h5>
            {% endif %}
        </div>
    </div>
</div>

{% include "pagination.html" %}
{% endblock %}

myfridge/dishes/templates/send_ingredients.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Send Ingredient {% endblock %}

{% block content %}
<div class="container-fluid vh-100 d-flex align-items-center justify-content-center">
  <div class="container">
    <form method="POST" class="needs-validation" novalidate>
      {% csrf_token %}
      {{form|crispy}}
      <button class="btn btn-primary" type="submit">Send</button>
    </form>
  </div>
</div>
{% endblock %}