myfridge/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"


urlpatterns = [
    path("post/create/", views.PostCreateView.as_view(), name="create_post"),
    path("post/update/<int:pk>/", views.PostUpdateView.as_view(), name="update_post"),
    path("post/delete/<int:pk>/", views.PostDeleteView.as_view(), name="delete_post"),
    path("", views.PostListView.as_view(), name="post_list"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path(
        "comment/create/<int:post_id>/",
        views.CommentCreateView.as_view(),
        name="create_comment",
    ),
    path(
        "comment/update/<int:pk>/",
        views.CommentUpdateView.as_view(),
        name="update_comment",
    ),
    path(
        "comment/delete/<int:pk>/",
        views.CommentDeleteView.as_view(),
        name="delete_comment",
    ),
]

myfridge/fak/urls.py
from django.urls import path
from . import views

app_name = "fak"


urlpatterns = [
    path("", views.FakListView.as_view(), name="fak_home"),
    path("fak/<int:pk>/", views.FakDetailsView.as_view(), name="fak_detail"),
    path("fak/create/", views.FakCreateView.as_view(), name="fak_create"),
    path("fak/update/<int:pk>/", views.FakUpdateView.as_view(), name="fak_update"),
    path("fak/delete/<int:pk>/", views.FakDeleteView.as_view(), name="fak_delete"),
    path("medicine/create", views.MedicineCreateView.as_view(), name="medicine_create"),
    path(
        "medicine/update/<int:pk>/",
        views.MedicineUpdateView.as_view(),
        name="medicine_update",
    ),
    path(
        "medicine/delete/<int:pk>/",
        views.MedicineDeleteView.as_view(),
        name="medicine_delete",
    ),
]

myfridge/myfridge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("", include("dishes.urls")),
    path("social/", include("social.urls")),
    path("contact/", include("contact.urls")),
    path("tools/", include("tools.urls")),
    path("fak/", include("fak.urls")),
    path("blog/", include("blog.urls")),
    path(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myfridge/users/urls.py
from django.urls import path
from . import views

app_name = "users"


urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path(
        "activate/<str:uidb64>/<str:token>/", views.send_activation_url, name="activate"
    ),
    path(
        "register/success", views.SuccessRegisterView.as_view(), name="success_register"
    ),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", views.LogoutUserView.as_view(), name="logout"),
    path("statute/", views.StatuteView.as_view(), name="statute"),
    path(
        "change_password/", views.ChangePasswordView.as_view(), name="change_password"
    ),
    path(
        "change_password_success/",
        views.SuccessPasswordChangeView.as_view(),
        name="success_password_change",
    ),
    path("delete_account/", views.DeleteAccountView.as_view(), name="delete_account"),
    path(
        "delete_account_success/",
        views.SuccessDeleteAccountView.as_view(),
        name="success_delete_account",
    ),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path(
        "profile/update/<int:pk>/",
        views.UpdateProfileView.as_view(),
        name="edit_profile",
    ),
    path(
        "profile/<int:pk>/detail",
        views.ProfileDetailView.as_view(),
        name="profile_detail",
    ),
    path("follow/<int:pk>/", views.FollowUserView.as_view(), name="follow"),
    path("unfollow/<int:pk>/", views.UnfollowUserView.as_view(), name="unfollow"),
    path(
        "profile/<int:user_id>/following",
        views.UserFollowingListView.as_view(),
        name="following",
    ),
    path(
        "profile/<int:user_id>/followers",
        views.UserFollowersListView.as_view(),
        name="followers",
    ),
    path("search/", views.search_users, name="search_users"),
    path("notifications/", views.notifications_list_view, name="notifications"),
    path(
        "notifications/mark_read/",
        views.notifications_mark_as_read,
        name="mark_notification_as_read",
    ),
]

myfridge/blog/models.py
from django.db import models
from users.models import CustomUser
from ckeditor.fields import RichTextField
from django.utils import timezone
from datetime import timedelta


class Post(models.Model):
    title = models.CharField(max_length=200)
    text = RichTextField(blank=True, null=True)
    image = models.ImageField(upload_to="images", default=None, blank=True, null=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return self.title

    @property
    def get_newest_label(self) -> bool:
        """
        Check if the post is newer than 2 days.
        :return: bool
        """
        if self.created_date > timezone.now() - timedelta(days=2):
            return True
        return False


class Comment(models.Model):
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-date_created"]

    def __str__(self):
        return f"{self.author} {self.post}"

    @property
    def get_newest_label(self) -> bool:
        """
        Check if the comment is newer than 12 hours.
        :return: bool
        """
        if self.date_created > timezone.now() - timedelta(hours=12):
            return True
        return False

myfridge/blog/forms.py
from django import forms


class DateSortingForm(forms.Form):
    CHOICES = (("1", "Newest"), ("2", "Oldest"))

    order_by = forms.ChoiceField(
        choices=CHOICES,
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["order_by"].label = ""

myfridge/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    UpdateView,
    ListView,
    DetailView,
)

from .models import Post, Comment
from typing import Any, Dict
from django.shortcuts import reverse
from django.contrib import messages
from .forms import DateSortingForm
from django.db.models import Q


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ("title", "text", "image")
    template_name = "post_create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user

        user = self.request.user
        user.points += 10
        user.save()
        messages.success(self.request, "Your post has been created! You got 10 points!")
        return super().form_valid(form)

    def get_success_url(self):
        post = get_object_or_404(Post, pk=self.object.pk)
        return reverse("blog:post_detail", kwargs={"pk": post.pk})

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return context


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ("title", "text", "image")
    template_name = "post_update.html"
    success_url = reverse_lazy("blog:post_list")

    def get_success_url(self):
        post = get_object_or_404(Post, pk=self.object.pk)
        return reverse("blog:post_detail", kwargs={"pk": post.pk})

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        if not queryset.exists():
            messages.error(
                self.request, "You are not authorized to edit this Shopping List."
            )
        messages.success(self.request, "Your post has been updated!")
        return queryset


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("blog:post_list")

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        if not queryset.exists():
            messages.error(
                self.request, "You are not authorized to delete this Shopping List."
            )
        messages.success(self.request, "Your post has been deleted!")
        return queryset


class PostListView(ListView):
    model = Post
    template_name = "post_list.html"
    paginate_by = 20

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get("q")
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) | Q(text__icontains=query)
            )

        order_by = self.request.GET.get("order_by")
        if order_by:
            if order_by == "1":
                queryset = queryset.order_by("created_date")
            if order_by == "2":
                queryset = queryset.order_by("-created_date")

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["order_by"] = DateSortingForm(self.request.GET)
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = "post_detail.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["comments"] = Comment.objects.filter(post=self.object)
        return context


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ("text",)
    template_name = "comment_create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post, pk=self.kwargs["post_id"])

        user = self.request.user
        user.points += 1
        user.save()
        messages.success(
            self.request, "Your comment has been created! You got 1 point!"
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.kwargs["post_id"]})


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ("text",)
    template_name = "comment_update.html"
    success_url = reverse_lazy("blog:post_list")

    def get_success_url(self):
        comment = get_object_or_404(Comment, pk=self.object.pk)
        return reverse("blog:post_detail", kwargs={"pk": comment.post.pk})

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        if not queryset.exists():
            messages.error(
                self.request, "You are not authorized to edit this Shopping List."
            )
        messages.success(self.request, "Your comment has been updated!")
        return queryset


class CommentDeleteView(DeleteView):
    model = Comment
    success_url = reverse_lazy("blog:post_list")

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        if not queryset.exists():
            messages.error(
                self.request, "You are not authorized to delete this Shopping List."
            )
        messages.success(self.request, "Your comment has been deleted!")
        return queryset

myfridge/blog/templates/comment_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Add comment {% endblock %}


{% block content %}


<div class="container mt-5 mb-5">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-success" type="submit">Add Comment</button>
    </form>
</div>

{% endblock %}

myfridge/blog/templates/comment_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Upadate Comment {% endblock %}


{% block content %}


<div class="container mt-5 mb-5">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-warning" type="submit">Update Comment</button>
    </form>
</div>

{% endblock %}

myfridge/blog/templates/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Create Meal Plan {% endblock %}


{% block content %}


<div class="container mt-5 mb-5">
  <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <button class="btn btn-success" type="submit">Add Post</button>
    </form>
</div>

{% endblock %}

myfridge/blog/templates/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Posts {{object.id}} {% endblock %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card my-4">
                <div class="card-body">
                    <h2 class="card-title">{{object.title}}</h2>
                        {% if object.author == user %}
                        <a href="{% url 'blog:update_post' object.id %}" class="btn btn-warning">Edit</a>
                        <form action="{% url 'blog:delete_post' object.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary mt-2">Delete</button>
                        </form>
                        {% endif %}
                    <p class="card-text"><a href="{% url 'users:profile_detail' object.author.id %}">{{object.author}}</a> | {{object.created_date}} | {% if object.get_newest_label%} <strong>Newest</strong> {%endif%}</p>
                    {% if object.image %}
                    <img class="card-img-top img-fluid mx-auto d-block" src="{{object.image.url}}">
                    {% endif %}
                    <p class="card-text mt-3">{{object.text|safe}}</p>
                </div>
            </div>

            <a href="{% url 'blog:create_comment' object.id %}" class="btn btn-primary">Add comment</a>
            {% if comments %}
            <div class="mt-4">
            {% for comment in comments %}
                <div class="card my-2">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'users:profile_detail' comment.author.id %}">{{comment.author}}</a> {% if comment.get_newest_label %} <strong>Newest</strong> {% endif %}</strong></h5>
                        <p class="card-text">{{comment.text}}</p>
                        {% if comment.author == user %}
                        <form action="{% url 'blog:delete_comment' comment.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary mt-2">Delete</button>
                        </form>

                        <a href="{% url 'blog:update_comment' comment.id %}" class="btn btn-warning">Edit</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            </div>
            {% else %}
            <p class="my-4">There are no comments yet</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

myfridge/blog/templates/post_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Posts {% endblock %}

{% block content %}
<div class="container-fluid min-vh-100">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form method="GET" class="form-inline my-2 my-lg-0">
                {{ order_by|crispy }}
                <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search..." aria-label="Search">
                <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <a href="{% url 'blog:create_post' %}" class="btn btn-success">Add Post</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 mx-auto">
            {% if object_list %}
                {% for data in object_list %}
                <div style="margin-top: 20px; margin-bottom: 20px">
                    <h2><a style="color: black; text-decoration: none;" href="{% url 'blog:post_detail' data.id %} ">{{ data.title }}</a></h2>
                    <p><a href="{% url 'users:profile_detail' data.author.id %}">{{ data.author }}</a> | {{ data.created_date }} | {% if data.get_newest_label %} <strong>Newest</strong> {% endif %} </p>
                    {% if data.image %}
                    <img style="width: 500px; height: 300px; object-fit: cover; " class="img-fluid mx-auto d-block " src="{{ data.image.url }}">
                    {% else %}
                    <img style="width: 500px; height: 300px; object-fit: cover; " class="img-fluid mx-auto d-block " src="https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg">
                    {% endif %}
                </div>
                {% endfor %}

            {% else %}
                <h2>There is no post yet...</h2>
            {% endif %}
        </div>
    </div>
</div>
{% include "pagination.html" %}
{% endblock %}

myfridge/blog/templates/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block meta_title%} MyFridge | Upadate Meal Plan {% endblock %}


{% block content %}


<div class="container mt-5 mb-5">
  <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <button class="btn btn-warning" type="submit">Update Post</button>
    </form>
</div>

{% endblock %}