myfridge/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"


urlpatterns = [
    path("post/create/", views.PostCreateView.as_view(), name="create_post"),
    path("post/update/<int:pk>/", views.PostUpdateView.as_view(), name="update_post"),
    path("post/delete/<int:pk>/", views.PostDeleteView.as_view(), name="delete_post"),
    path("", views.PostListView.as_view(), name="post_list"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path(
        "comment/create/<int:post_id>/",
        views.CommentCreateView.as_view(),
        name="create_comment",
    ),
    path(
        "comment/update/<int:pk>/",
        views.CommentUpdateView.as_view(),
        name="update_comment",
    ),
    path(
        "comment/delete/<int:pk>/",
        views.CommentDeleteView.as_view(),
        name="delete_comment",
    ),
]

myfridge/dishes/urls.py
from django.urls import path
from . import views

app_name = "dishes"


urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("dish/<int:pk>/", views.DishDetailView.as_view(), name="dish-detail"),
    path("dish/random/", views.RandomDishView.as_view(), name="random-dish"),
    path("dish/create/", views.DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/delete", views.DeleteDishView.as_view(), name="dish-delete"),
    path("dish/<int:pk>/update", views.UpdateDishView.as_view(), name="dish-update"),
    path(
        "dish/<int:pk>/send-ingredients",
        views.SendIngredientsView.as_view(),
        name="send-ingredients",
    ),
]

myfridge/fak/urls.py
from django.urls import path
from . import views

app_name = "fak"


urlpatterns = [
    path("", views.FakListView.as_view(), name="fak_home"),
    path("fak/<int:pk>/", views.FakDetailsView.as_view(), name="fak_detail"),
    path("fak/create/", views.FakCreateView.as_view(), name="fak_create"),
    path("fak/update/<int:pk>/", views.FakUpdateView.as_view(), name="fak_update"),
    path("fak/delete/<int:pk>/", views.FakDeleteView.as_view(), name="fak_delete"),
    path("medicine/create", views.MedicineCreateView.as_view(), name="medicine_create"),
    path(
        "medicine/update/<int:pk>/",
        views.MedicineUpdateView.as_view(),
        name="medicine_update",
    ),
    path(
        "medicine/delete/<int:pk>/",
        views.MedicineDeleteView.as_view(),
        name="medicine_delete",
    ),
]

myfridge/myfridge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("users.urls")),
    path("", include("dishes.urls")),
    path("social/", include("social.urls")),
    path("contact/", include("contact.urls")),
    path("tools/", include("tools.urls")),
    path("fak/", include("fak.urls")),
    path("blog/", include("blog.urls")),
    path(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myfridge/tools/urls.py
from django.urls import path
from . import views

app_name = "tools"


urlpatterns = [
    path("", views.ToolsHomePageTemplateView.as_view(), name="tools_home"),
    path("bmi/", views.bmiView, name="bmi"),
    path("shopping_list/", views.ShoppingListView.as_view(), name="shopping_list"),
    path(
        "shopping_list/create/",
        views.ShoppingListCreateView.as_view(),
        name="shopping_list_create",
    ),
    path(
        "shopping_list/update/<int:pk>/",
        views.ShoppingListUpdateView.as_view(),
        name="shopping_list_update",
    ),
    path(
        "shopping_list/delete/<int:pk>/",
        views.ShoppingListDeleteView.as_view(),
        name="shopping_list_delete",
    ),
    path("caloric-needs/", views.caloricNeedsView, name="caloric-needs"),
    path("perfect-weight/", views.perfect_weight_view, name="perfect-weight"),
    path("meal/create", views.MealCreateView.as_view(), name="meal_create"),
    path("meal/update/<int:pk>", views.MealUpdateView.as_view(), name="meal_update"),
    path("meal/delete/<int:pk>", views.MealDeleteView.as_view(), name="meal_delete"),
    path("meal/details/<int:pk>", views.MealDetailView.as_view(), name="meal_details"),
    path(
        "meal-plan/create",
        views.MealDailyPlanCreateView.as_view(),
        name="meal_plan_create",
    ),
    path(
        "meal-plan/update/<int:pk>",
        views.MealDailyPlanUpdateView.as_view(),
        name="meal_plan_update",
    ),
    path(
        "meal-plan/delete/<int:pk>",
        views.MealDailyPlanDeleteView.as_view(),
        name="meal_plan_delete",
    ),
    path(
        "meal-plan/details/<int:pk>",
        views.MealDailyPlanDetailView.as_view(),
        name="meal_plan_details",
    ),
    path(
        "meal-plan/list", views.MealDailyPlanListView.as_view(), name="meal_plan_list"
    ),
    path(
        "daily-statistics/create",
        views.UserDailyStatisticsCreateView.as_view(),
        name="daily_statistics_create",
    ),
    path(
        "daily-statistics/<int:pk>/update",
        views.UserDailyStatisticsUpdateView.as_view(),
        name="daily_statistics_update",
    ),
    path(
        "daily-statistics",
        views.UserDailyStatisticsReportView.as_view(),
        name="daily_statistics_report",
    ),
]

myfridge/users/urls.py
from django.urls import path
from . import views

app_name = "users"


urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path(
        "activate/<str:uidb64>/<str:token>/", views.send_activation_url, name="activate"
    ),
    path(
        "register/success", views.SuccessRegisterView.as_view(), name="success_register"
    ),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", views.LogoutUserView.as_view(), name="logout"),
    path("statute/", views.StatuteView.as_view(), name="statute"),
    path(
        "change_password/", views.ChangePasswordView.as_view(), name="change_password"
    ),
    path(
        "change_password_success/",
        views.SuccessPasswordChangeView.as_view(),
        name="success_password_change",
    ),
    path("delete_account/", views.DeleteAccountView.as_view(), name="delete_account"),
    path(
        "delete_account_success/",
        views.SuccessDeleteAccountView.as_view(),
        name="success_delete_account",
    ),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path(
        "profile/update/<int:pk>/",
        views.UpdateProfileView.as_view(),
        name="edit_profile",
    ),
    path(
        "profile/<int:pk>/detail",
        views.ProfileDetailView.as_view(),
        name="profile_detail",
    ),
    path("follow/<int:pk>/", views.FollowUserView.as_view(), name="follow"),
    path("unfollow/<int:pk>/", views.UnfollowUserView.as_view(), name="unfollow"),
    path(
        "profile/<int:user_id>/following",
        views.UserFollowingListView.as_view(),
        name="following",
    ),
    path(
        "profile/<int:user_id>/followers",
        views.UserFollowersListView.as_view(),
        name="followers",
    ),
    path("search/", views.search_users, name="search_users"),
    path("notifications/", views.notifications_list_view, name="notifications"),
    path(
        "notifications/mark_read/",
        views.notifications_mark_as_read,
        name="mark_notification_as_read",
    ),
]

myfridge/myfridge/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block meta_title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</head>
<body>
    {% include "navigation_bar.html" %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} mt-2" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}

    {% endblock %}


    {% include "footer.html" %}
</body>
</html>

myfridge/myfridge/templates/footer.html
<footer class="text-center text-lg-start bg-light text-muted">
    <section class="">
      <div class="container text-center text-md-start mt-4">
        <div class="row mt-5">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4 mt-3">
              <i class="fas fa-gem me-3"></i>MyFridge
            </h6>
            <p>
                Ut ea facere quas ducimus. Dolore excepturi corrupti reprehenderit qui facilis. Et officiis est qui cumque voluptates ullam rerum qui.
            </p>
          </div>

          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4 mt-3">
              About me
            </h6>
            <p>
              <a href="https://github.com/DEENUU1/" class="text-reset">GitHub</a>
            </p>
            <p>
              <a href="https://www.linkedin.com/in/kacper-wlodarczyk/" class="text-reset">LinkedIn</a>
            </p>
          </div>
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4 mt-3">
              Useful links
            </h6>
            <p>
              <a href="{% url 'dishes:home' %}" class="text-reset">Dishes</a>
            </p>
            <p>
              <a href="{% url 'tools:tools_home' %}" class="text-reset">Tools</a>
            </p>
            <p>
              <a href="{% url 'fak:fak_home' %}" class="text-reset">First aid kit</a>
            </p>
            <p>
              <a href="{% url 'social:user-ranking' %}" class="text-reset">Ranking</a>
            </p>
            <p>
              <a href="{% url 'blog:post_list' %}" class="text-reset">Blog</a>
            </p>
          </div>
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold mb-4 mt-3">Contact</h6>
            <p>Address: New York, NY 10012, US</p>
            <p>Email: info@example.com</p>
            <p>Phone number:  01 234 567 89</p>
            <p>
              <a href="{% url 'contact:contact' %}" class="text-reset">Contact form</a>
            </p>
          </div>
        </div>
      </div>
    </section>
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2023 Copyright:
      <a class="text-reset fw-bold" href="https://github.com/DEENUU1/">Kacper Włodarczyk</a>
    </div>
  </footer>

myfridge/myfridge/templates/navigation_bar.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img
          src="https://simpleicon.com/wp-content/uploads/dish.png"
          height="25"
          alt="MDB Logo"
          loading="lazy"
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dishes:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'fak:fak_home' %}">Fak</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'social:user-ranking' %}">Ranking</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tools:tools_home' %}">Tools</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">

      <!-- Notifications -->
      {% if user.is_authenticated %}
        <a
          class="text-reset me-3"
          href="{% url 'users:notifications' %}"
        >
          <i class="fas fa-bell"></i>
          {% if unread_count %}
          <span class="badge rounded-pill badge-notification bg-danger">{{ unread_count }}</span>
          {% endif %}
        </a>
      {% endif %}
      <!-- Avatar -->
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          Profile
        </button>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
          {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'users:profile' %}">My profile</a></li>
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="dropdown-item" href="{% url 'users:register' %}">Register</a></li>
            <li><a class="dropdown-item" href="{% url 'users:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

myfridge/myfridge/templates/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.previous_page_number}}">previous</a>
      </li>
    {% endif %}
      <li class="page-item"><a class="page-link" href="#">{{page_obj.number}} of {{page_obj.paginator.num_pages }}</a></li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
      </li>
    {% endif %}
    </ul>
</nav>